// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type ApiKey struct {
	ID         pgtype.UUID
	UserID     pgtype.UUID
	Name       string
	KeyHash    string
	RevokedAt  pgtype.Timestamp
	LastUsedAt pgtype.Timestamp
	CreatedAt  pgtype.Timestamp
}

type User struct {
	ID           pgtype.UUID
	Email        string
	PasswordHash string
	CreatedAt    pgtype.Timestamp
}
