// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: query.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createApiKey = `-- name: CreateApiKey :one
INSERT INTO api_keys (user_id, name, key_hash)
VALUES ($1, $2, $3)
RETURNING id, user_id, name, key_hash, revoked_at, last_used_at, created_at
`

type CreateApiKeyParams struct {
	UserID  pgtype.UUID
	Name    string
	KeyHash string
}

func (q *Queries) CreateApiKey(ctx context.Context, arg CreateApiKeyParams) (ApiKey, error) {
	row := q.db.QueryRow(ctx, createApiKey, arg.UserID, arg.Name, arg.KeyHash)
	var i ApiKey
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.KeyHash,
		&i.RevokedAt,
		&i.LastUsedAt,
		&i.CreatedAt,
	)
	return i, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (email, password_hash)
VALUES ($1, $2)
RETURNING id, email, password_hash, created_at
`

type CreateUserParams struct {
	Email        string
	PasswordHash string
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser, arg.Email, arg.PasswordHash)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.CreatedAt,
	)
	return i, err
}

const getApiKeyByHash = `-- name: GetApiKeyByHash :one
SELECT id, user_id, name, key_hash, revoked_at, last_used_at, created_at From api_keys
WHERE key_hash = $1 AND revoked_at IS NULL
`

func (q *Queries) GetApiKeyByHash(ctx context.Context, keyHash string) (ApiKey, error) {
	row := q.db.QueryRow(ctx, getApiKeyByHash, keyHash)
	var i ApiKey
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.KeyHash,
		&i.RevokedAt,
		&i.LastUsedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getApiKeysByUser = `-- name: GetApiKeysByUser :many
SELECT id, name, last_used_at, revoked_at, created_at
FROM api_keys
WHERE user_id = $1
`

type GetApiKeysByUserRow struct {
	ID         pgtype.UUID
	Name       string
	LastUsedAt pgtype.Timestamp
	RevokedAt  pgtype.Timestamp
	CreatedAt  pgtype.Timestamp
}

func (q *Queries) GetApiKeysByUser(ctx context.Context, userID pgtype.UUID) ([]GetApiKeysByUserRow, error) {
	rows, err := q.db.Query(ctx, getApiKeysByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetApiKeysByUserRow
	for rows.Next() {
		var i GetApiKeysByUserRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.LastUsedAt,
			&i.RevokedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, email, password_hash, created_at FROM users WHERE email = $1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.CreatedAt,
	)
	return i, err
}

const revokeApiKey = `-- name: RevokeApiKey :exec
UPDATE api_keys
SET revoked_at = CURRENT_TIMESTAMP
WHERE id = $1
AND user_id = $2
AND revoked_at IS NULL
`

type RevokeApiKeyParams struct {
	ID     pgtype.UUID
	UserID pgtype.UUID
}

func (q *Queries) RevokeApiKey(ctx context.Context, arg RevokeApiKeyParams) error {
	_, err := q.db.Exec(ctx, revokeApiKey, arg.ID, arg.UserID)
	return err
}
